server:
    port: 8083
    address: localhost
    servlet:
        context-path: /store
spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5433/store
        username: store
        password:
    jpa:
        properties:
            hibernate.temp.use_jdbc_metadata_defaults: false