server:
    port: 8082
    address: localhost
    servlet:
        context-path: /inventory
spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5432/inventory
        username: inventory
        password:
    jpa:
        properties:
            hibernate.temp.use_jdbc_metadata_defaults: false