version: '2'
services:
    angular-app:
        image: baking/angular:default
        container_name: angular
        ports:
            - 8080:80
        depends_on:
          - book-api
          - number-api
    book-api:
        image: baking/book-api:default
        container_name: book-api
        ports:
            - 8081:8081
        logging:
          driver: gelf
          options:
            gelf-address: udp://localhost:12201
        depends_on:
          - elk
          - number-api
    number-api:
        image: baking/number-api:default
        container_name: number-api
        ports:
            - 8084:8084
        logging:
          driver: gelf
          options:
            gelf-address: udp://localhost:12201
        depends_on:
          - elk
    elk:
        image: radcortez/elk
        container_name: elk
        ports:
            - 5601:5601
            - 9200:9200
            - 5044:5044
            - 12201:12201/udp
        volumes:
          - ./infra/elk/:/etc/logstash/conf.d/
